spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          #brokers: kafka-broker-01-dev.sistemafiergs.com.br,kafka-broker-02-dev.sistemafiergs.com.br,kafka-broker-03-dev.sistemafiergs.com.br
        bindings:
          test-input:
            consumer:
              resetOffsets: true
      bindings:
        piec-getbankslip:
          destination: piec-getbankslip
          contentType: application/json
        piec-sendbankslip:
          destination: piec-sendbankslip
          contentType: application/json
