spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-broker-01-dev.sistemafiergs.com.br,kafka-broker-02-dev.sistemafiergs.com.br,kafka-broker-03-dev.sistemafiergs.com.br
        bindings:
          test-input:
            consumer:
              resetOffsets: true
      bindings:
        piec-getbankslip:
          destination: piec-getbankslip
          contentType: application/json

server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: changeit
    key-alias: javaclient
    trust-store: classpath:truststore.jks
    trust-store-password: changeit
    client-auth: need
